version: '3.3'

services:
  project_name:
    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
      - mongo

    ports: 
      - 5000:5000
    depends_on:
      - mongo

  mongo:
    image: mongo
